import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Manrope ,Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Navbar } from "@/components/navbar";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight:["400","500","600","700"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
   weight:["400","500","600","700"]

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" suppressHydrationWarning>
        <head/>
         <body className= {`${manrope.variable} ${inter.variable} min-h-screen antialiased`}>
        <ThemeProvider 
        attribute={"class"} 
        defaultTheme="system" 
        enableSystem disableTransitionOnChange 
       >
          <Navbar/>
         <main className="min-h-screen bg-background text-foreground">
  {children}
</main>
        </ThemeProvider>
        </body>
    </html>
      
    
      
  );
}
